### ISSUE TITLE
Light doesn't turn off

### ISSUE THREAD

**Issue by Barzille** [j-a-n/homematic-addon-hue#1]
Great plugin :)
But after I successfully turned on a light, 
I cannot turn it off using:

/usr/local/addons/hue/hue.tcl secretID light 9 on:false

Using 
/usr/local/addons/hue/hue.tcl secretID

 light 9 on:true hue:1000 sat:200 bri:100
for turning on works pretty fine

<img width="1426" alt="screenshot_88" src="https://cloud.githubusercontent.com/assets/1096322/23093773/2b658858-f5ec-11e6-859e-9ccaad00cc7b.png">

**Comment by j-a-n** [comment]
Thanks for reporting, fixed in version 0.8.10.
