### ISSUE TITLE
Lampen lassen sich nach Update nicht mehr steuern

### ISSUE THREAD

**Issue by CharlyFive** [j-a-n/homematic-addon-hue#10]
UPDATE:
Problem gelöst. Ein Neustart der CCU war notwenig damit es wieder funktioniert. Hier greift wohl die aktuelle Methode das nach installieren oder Updates des Plugins ein abmelden aus der WebUI stattfindet nicht. Also benötigt dieses Plugin im Moment nach einem Update einen reboot der CCU?

Hallo, ich habe ein Update auf 2.0.8 gemacht und seitdem kann ich die Lampe nicht mehr über die CUxD Fernbedienung steuern.

Wenn ich in das Hue Plugin WebUI gehe und dort auf Test klicke dann blinken alle Lampen, die Verbindung steht also.

Hatt es immer so eingebunden:
/usr/local/addons/hue/hue.tcl 001788fffea5e4e4 Group 1 scene:mikRq7rjSIJBQuW
(CUX4000001 / 16 TFB)
<img width="686" alt="Bildschirmfoto 2019-06-02 um 23 07 45" src="https://user-images.githubusercontent.com/23129385/58767432-410f9780-858b-11e9-84fa-7d6f1a632606.png">

Wenn ich dann hier auf der Fernbedienung den kurzen Tastendruck betätige passier nichts mehr. Vor dem Update wird halt die Scene geschaltet und die Lampen wurden entsprechend eingeschaltet ect.
<img width="900" alt="Bildschirmfoto 2019-06-02 um 23 08 24" src="https://user-images.githubusercontent.com/23129385/58767446-6f8d7280-858b-11e9-8250-4cb50a363351.png">  

Die Scene "mikRq7rjSIJBQuW" gibt es auch noch:
<img width="500" alt="Bildschirmfoto 2019-06-02 um 23 05 20" src="https://user-images.githubusercontent.com/23129385/58767415-eaa25900-858a-11e9-9d9e-f94c1fa3bea2.png">

**Comment by j-a-n** [comment]
Wahrscheinlich lief der hued nicht.
