### ISSUE TITLE
Verzögerung beim Schalten der Lampen

### ISSUE THREAD

**Issue by honeyworld2** [j-a-n/homematic-addon-hue#11]
Hallo Jan,

erstmal ganz herzlichen Dank für die tolle Arbeit mit dem PlugIN!
Ich bin jüngst auf die Version > 2.0 umgestiegen. Seitdem habe ich das Phänomen, dass Schaltvorgänge (ein/aus, Farbe ändern etc). erst nach mehreren Sekunden umgesetzt werden (auch bei direkter Eingabe im UI des AddOn). Die Zeit ist dabei sehr unterschiedlich von 1 Sekunden bis zu über 10 Sekunden. Eventuell eine Idee woran das liegen könnte?

Danke und VG!

**Comment by j-a-n** [comment]
Hallo!

Die Philips Hue API lässt nur 10 Gruppen-Kommandos pro 10 Sekunden zu. Wird das Limit nicht eingehalten, werden Befehle u.U. gar nicht ausgeführt. Die neueren Versionen des Plugins halten sich an dieses Limit. Nach ca. 8 Kommandos wird daher erst mal eine kleine Pause eingelegt. Sollte such im Log-File ersichtlich sein.

Grüße
Jan
