### ISSUE TITLE
Restart daemon using script

### ISSUE THREAD

**Issue by marvingrieger** [j-a-n/homematic-addon-hue#12]
Hi,
sometimes the lights won't respond to a command. 
In that case, I need to restart the daemon and everything works fine again.

Is there a way to restart the daemon by using a script within a CCU program? 
So far, I always restart the daemon using the Web UI.

Best regards,

Marvin

**Comment by j-a-n** [comment]
Hi Marvin,

would be better to fix the issue.
What is in the log file while commands do not work?

Regards
Jan

**Comment by marvingrieger** [comment]
Unfortunately, logging was disabled - now it is turned on. If I get some meaningful logs, I'll post them here.

However, in my experience bugs may always occur and need time to be located and fixed 😉 Therefore, I would appreciate to have an automated option to restart.

**Comment by j-a-n** [comment]
Just execute `/usr/local/addons/hue/hued.tcl` and the daemon will restart.
