### ISSUE TITLE
Frage zu "Create CUxD-dimmer"

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#13]
Hi! Erstmal ein dickes DANKE für diese Erweiterung. Heute habe ich zum ersten Mal u.a. die Funktion "Create CUxD-dimmer" entdeckt, einfach klasse! Nun die Frage dazu:

Ist es richtig, dass das Device als Jalousiesteuerung "HM-LC-Ja1PBU-FM" angelegt wird?

Ich denke mal Ja, sonst wäre es ja wahrscheinlich nicht so ^^

Die Andere Frage: Muss das so sein? Denn die Steuerung in einer App sieht dann etwas komisch aus ^^

![IMG_4052](https://user-images.githubusercontent.com/25386824/67627282-3f57b080-f859-11e9-9d6f-9f45b36093dd.jpg)

![IMG_4053](https://user-images.githubusercontent.com/25386824/67627281-3f57b080-f859-11e9-9d09-248a31234ab8.PNG)

Ist es evtl. möglich, dies als richtigen Dimmer abzubilden?

**Comment by j-a-n** [comment]
Hallo,
nein, das soll so nicht sein.
Welche CUxD-Version setzt Du ein?

**Comment by j-a-n** [comment]
Hat sich mit CUxD 2.3.4 geändert.
Behoben in hue addon 2.1.12.
