### ISSUE TITLE
Tmp out of memory - Log-File rotation

### ISSUE THREAD

**Issue by marvingrieger** [j-a-n/homematic-addon-hue#15]
Hello,

on my RaspberryMatic, the Hue Addon stopped working after some time. Also rebooting it does not help, since the daemon was killed seconds after restarting.

When trying to find out what's going on, I noticed that the last log entry was truncated pretty hard:

<img width="1673" alt="Bildschirmfoto 2019-11-19 um 08 37 44" src="https://user-images.githubusercontent.com/1997765/69126657-f9cd8280-0aa8-11ea-9a45-6de4235e121a.png">

When checking the available disk space, I noticed that _var_ was out of memory, due to the size of the hue-logfile:

<img width="551" alt="Bildschirmfoto 2019-11-19 um 08 37 01" src="https://user-images.githubusercontent.com/1997765/69126868-72344380-0aa9-11ea-9582-36fcbc7d956f.png">

After deleting the log-file, the add-on works again.

Is it possible, that there is no automatic log rotation in place, or did I miss some kind of configuration anywhere?

**Comment by j-a-n** [comment]
Yes, that is unfavourable.
Maximum log file size is now 1MB in version 2.1.17.
