### ISSUE TITLE
Webinterface auf deutsch?

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#16]
Hallo! Wäre es ggf. möglich, das Webinterface und die darin enthaltenen Beschreibungen (Beispiele) auf deutsch zu übersetzen?

**Comment by j-a-n** [comment]
Meinst Du die README.md?
Pull Requests für eine deutsche README sind natürlich willkommen.

**Comment by LevelOne2k** [comment]
Hi, ich meinte diese Seite und Erklärung unten:
<img width="1143" alt="Bildschirmfoto 2019-11-20 um 21 38 23" src="https://user-images.githubusercontent.com/25386824/69276176-3d75d880-0bde-11ea-81af-5876e98f3252.png">
<img width="1142" alt="Bildschirmfoto 2019-11-20 um 21 38 34" src="https://user-images.githubusercontent.com/25386824/69276187-41a1f600-0bde-11ea-96db-e5211d7bcd2f.png">

**Comment by j-a-n** [comment]
Ist umgesetzt in Version 2.2.0

**Comment by LevelOne2k** [comment]
Vielen Dank!
