### ISSUE TITLE
dutycycle

### ISSUE THREAD

**Issue by fighterzg6** [j-a-n/homematic-addon-hue#17]
the last version is funky. duty cycle 99%.
install 2.1.0 Andy the duty cycle works correctly

**Comment by j-a-n** [comment]
Why do you think that the addon is responsible for the duty cycle?
This addon should not have any effect on the CCU duty cycle.

**Comment by fighterzg6** [comment]
hello, I do not know! it was like that.

**Comment by JackJoeJim** [comment]
Salud,
i've got the same case. The first version I installed was 1.1.17 and it already happend. Version 2.2.0 doesn't solve the problem.
After restarting the CCU the Duty Cycle is around 22 %. After round about 10 minutes it reaches 99 % and doesn't decrease anymore.

In my case there is another problem as well. After adding the bridge, the info button does not give a result. By clicking on the button, a pop up called "Info" pops out for less than a second and immediately closes down again.
Clicking on "CUxD-Gerätezuordnung anzeigen" gives back an error as well:
Ein Fehler ist aufgetreten: Transport error on xmlrpc call listDevices to xmlrpc_bin://127.0.0.1:8701: Error in XmlRpcClient::writeRequest: write error (error 111).

No idea, if both issues are linked.


Thanks for helping

JackJoe

**Comment by j-a-n** [comment]
@JackJoeJim : do you have a CUxD installed and running?

**Comment by JackJoeJim** [comment]
positive: "Hue-Daemon läuft (pid: 663)"

**Comment by JackJoeJim** [comment]
Thanks for helping!!

**Comment by fighterzg6** [comment]
wenn ich auf die version 2.2.2 update habe ich sofort wieder dutycycle 99% . 
bin zurück auf version 2.1.17 und alles ist wieder ok!

**Comment by fighterzg6** [comment]
when i update to version 2.2.2 i immediately return dutycycle 99%.
I'm back on version 2.1.17 and everything is ok again!

**Comment by j-a-n** [comment]
Is this issue resolved?
