### ISSUE TITLE
Link in der Zusatzsoftware Ansicht in einem neuen Tab öffnen

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#18]
Hallo!

Bitte hier den Link in einem neuen Tab öffnen wenn man drauf klickt. Bisher öffnet er sich im gleichen Fenster.

Danke!

<img width="798" alt="Bildschirmfoto 2020-01-09 um 02 38 00" src="https://user-images.githubusercontent.com/25386824/72030408-2de34980-3289-11ea-8ad0-66784dd2eb34.png">

**Comment by j-a-n** [comment]
Hallo,

welchen Link meinst Du?

**Comment by LevelOne2k** [comment]
Rechts auf dem Screenshot den
