### ISSUE TITLE
HueLivingColors LLC001

### ISSUE THREAD

**Issue by EagleeyeKai** [j-a-n/homematic-addon-hue#19]
Hi,
thanks for providing your plugin to get bidirectional communication with homematic!
I just set up my Hue lights through your plugin. Almost everything works as desired.
However, I have a Hue LivingColors (model LLC001), which does not work properly. The lamp is accessible and can be controlled in both brightness and color. But the color temperature or saturation cannot be controlled. The channel is available, but it is not possible to change the value.
I have read that the older Hue lamps speak a different protocol or require the colour information in a different format. Do you know anything about this and is it possible to solve the problem?

Many greetings

**Comment by j-a-n** [comment]
Could you please provide all the information about the light from the addon info page (capabilities, state, ...)?

Are you able to change the color via XY (i.e.: 0.1, 0.1) on the control dialog of the addon?
![grafik](https://user-images.githubusercontent.com/11510943/72209122-58ace800-34ab-11ea-8aa6-1aaf7c1a81f1.png)

**Comment by EagleeyeKai** [comment]
Yes, I am able to control the light via the control dialog and the XY parameter.

**Comment by j-a-n** [comment]
Please try version 3.0.0.
