### ISSUE TITLE
Sowas wie "ha-bridge" für die CCU nachbauen

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#20]
Hallo!

Wäre sowas möglich das Du sowas baust nur für die CCU/RaspberryMatic? Das wäre echt geil!

Vielleicht könnte man das ganze ins HomeMatic Add-on für Philips Hue von Dir intrigieren.

https://github.com/bwssytems/ha-bridge

**Comment by HookHM** [comment]
Oh jaaaa das wäre mega!!!! Was sagst Du dazu @j-a-n

**Comment by TheRealTremes** [comment]
Jau, da würde ich auch zu 100% für stimmen. Das wäre der Kracher! Dann müsste man endlich nicht mehr noch ein Gerät extra in Betrieb haben und hätte alles auf einem.

@j-a-n Damit kann man dann Hue Lampen emulieren und damit dann z.B. nicht Hue Geräte auf z.b. den Harmony Haustasten (Lampentaste, Steckdosentaste, Dimmtasten) legen. Z.B. könnte man dann einen Homematic Dimmer (oder was man will) mit diesen Tasten steuern. Die Harmony denkt dabei, es wären Hue Geräte. Dimmen und alles was dazu gehört funktioniert dann.

**Comment by LevelOne2k** [comment]
@j-a-n & @TheRealTremes genau so wäre das.

Die ha-brudge holt sich dabei auch die original Hue lampen aus der original Hue Bridge raus, damit man diese dann auch darüber steuern kann. Die ha-bridge ist sozusagen eine offene Hue Bride mit der man auch keine Zigbee Geräte steuern kann sondern alles was man will.

Ich kann z.B. dann mit der Harmony Fernbedienung über die Steckdosentaste mein Alarmsystem von Homematic aktivieren oder mit einem langen Tastendruck deaktivieren.

**Comment by Kinzal16** [comment]
Das jemand auf die Idee kommt das es die ha-bridge auch für die CCU geben könnte, HAMMER. Und dann eventuell noch in das CCU Hue Addon von @j-a-n intrigiert noch besser.

Aber auch getrennt als eigenständiges Addon für die CCU wäre schon ein Traum. Habe mir die Ha Bridge schon öfters für die CCU als Addon gewünscht, jetzt sind wir vielleicht ein klizekleines Stück an diesem Wunsch das er erfüllt wird.

**Comment by j-a-n** [comment]
Verstehe. Wäre echt ne schöne Sache. Da es aber quasi genau das Gegenteil von dem ist, was dieses Addon macht, gehört es in ein eigenes Addon. Mal sehen ob jemand die Idee aufgreift ;)

**Comment by AdlerCentauri** [comment]
JA bitte bitte bitte. Da wäre ich sogar bereit für zu zahlen.

**Comment by LevelOne2k** [comment]
@j-a-n als eigenständiges Add-on wäre auch mega ok. Würdest du dich denn evtl. dran wagen? So wie ich das hier sehe, besteht ja reichlich Interesse daran.

**Comment by TheRealTremes** [comment]
Ja würdest du das machen @j-a-n

**Comment by CharlyFive** [comment]
Ja das wäre wirklich fantastisch. Was sagst du dazu @j-a-n ?

**Comment by nubbel7404** [comment]
Das würde mich auch sehr freuen @j-a-n

**Comment by j-a-n** [comment]
Habe mir ha-bridge gerade mal angeschaut.
Man könnte wohl einfach ein homematic-Plugin für ha-bridge programmieren.

**Comment by LevelOne2k** [comment]
Baust du das Plugin @j-a-n ?

**Comment by j-a-n** [comment]
Dafür habe ich momentan leider keine Zeit.
