### ISSUE TITLE
Helligkeit, Farbton, Farbtemperatur CUxD Dimmer Gruppieren

### ISSUE THREAD

**Issue by LarsSab** [j-a-n/homematic-addon-hue#21]
Hallo,
es wäre schön, wenn man Gruppierte Lampen über einen Schalter bedienen könnte und nicht wie aktuell über drei einzelne.

Viele Grüße
![IMG_9316](https://user-images.githubusercontent.com/50446568/72258190-b6f1dc00-360d-11ea-9ae7-273cd05c61cd.PNG)

**Comment by j-a-n** [comment]
Die virtuellen Geräte werden vom CUxD bereitgestellt.
Eine entsprechende Änderung müsste im CUxD vorgenommen werden.
