### ISSUE TITLE
Fehlermeldung nach Update auf 2.3.8: No such file or directory

### ISSUE THREAD

**Issue by DannyLG-21** [j-a-n/homematic-addon-hue#22]
Nach dem Update auf 2.3.8 erscheint beigefügte Fehlermeldung auf CCU2 (Softwareversion 2.49.18) Ansonsten scheint auf den ersten Blick alles zu funktionieren. Was kann man tun?
Danke!
Viele Grüße
Daniel

<img width="1152" alt="Fehlermeldung" src="https://user-images.githubusercontent.com/59890286/72371844-74abc600-3705-11ea-8f9e-88cbd0be1a83.png">

**Comment by j-a-n** [comment]
Hallo Daniel,

das liegt an dem curl-Binary aus dem CUxD.
Vielleicht schaust Du mal, ob es einen neuere CUxD-Version gibt.
Es sollte aber nur die Suche nach neuen Hue-Bridges nicht funktionieren.

**Comment by DannyLG-21** [comment]
Hallo, danke für die Info! Leider keine neue CUxD-Version verfügbar. Kann es eventuell an einem falschen Suchpfad liegen? siehe hier:
https://homematic-forum.de/forum/viewtopic.php?f=26&t=55113&hilit=curl+binary
Danke!!

**Comment by j-a-n** [comment]
Bitte einmal die Version 2.3.9 testen.

**Comment by DannyLG-21** [comment]
Installiert und getestet, Fehlermeldung ist weg, danke!! Schalten funktioniert auch. Das Hinzufügen neuer Geräte habe ich nicht getestet.
