### ISSUE TITLE
Temporary Solution: Socket Timeout CCU3

### ISSUE THREAD

**Issue by mistermakc** [j-a-n/homematic-addon-hue#23]
Hi Jan, 

I probably found a temporary solution to fix the timeouts of the CCU and hence the delays in the program execution/state change of the lights.

I changed the polling interval from 5 to 60 seconds. Now everything works flawlessly. Hope that works for others as well.

Best Max

**Comment by j-a-n** [comment]
Hi Max,

thanks for the hint.
Please try if version 2.4.0 is working better with short polling intervals.

Regards
Jan

**Comment by mistermakc** [comment]
Hi Jan,

Unfortunately since installing the new version, nothing works anymore. In the Logs i just get the message: 

Error: can not find channel named "stderr" - NONE - can not find channel named "stderr"
    while executing
"puts stderr $msg"
    (procedure "write_log" line 8)
    invoked from within
"write_log 0 "api request: ${ip} - ${method} - ${path} - ${data}""
    (procedure "api_request" line 13)
    invoked from within
"api_request $type $bridge(ip) $bridge(port) $bridge(username) $method $path $data"
    invoked from within
"hue::request "status" $bridge_id "GET" "/${obj_type}s""
    (procedure "check_update" line 22)
    invoked from within
"check_update"

What can I do?

**Comment by j-a-n** [comment]
Sorry, please try version 2.4.1
