### ISSUE TITLE
 homematic-addon-hue für Debmatic

### ISSUE THREAD

**Issue by AndynordSee** [j-a-n/homematic-addon-hue#24]
Moin, 

bin schon seit längerem begeistert von deinem Addon, vielen Dank für dein Arbeit. 
Würde mich sehr freuen wenn es möglich wäre dein Addon unter [Debmatic](https://github.com/alexreinert/debmatic) nutzen zu können.

**Comment by diesermaba** [comment]
Hey j-a-n,

ich bin auch wie mein Vorredner gerade dabei von pivccu3 auf debmatic umzusteigen und der einzige Wermutstropfen ist der, dass dein Addon unter debmatic nicht funktioniert. 

Ist das eventuell was in Planung?

**Comment by j-a-n** [comment]
Hi,

ich habe jetzt mal ein Debian-Paket zusammengebaut.
Könnt ihr gerne mal testen.
[hue_amd64.deb](https://github.com/j-a-n/homematic-addon-hue/raw/master/hue_amd64.deb)

Grüße
Jan

**Comment by AndynordSee** [comment]
Moin Jan vielen Dank, Versuche es heute Mal zu testen ;-))
