### ISSUE TITLE
"Create CUxD-dimmer" verschwunden

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#26]
Hallo @j-a-n gibt es die Funktion "Create CUxD-dimmer" nicht mehr? Ich sehe sie um Hue Addon Webif nicht mehr.

Installierte Version ist die 3.0.1

**Comment by j-a-n** [comment]
Doch, sollte es geben.
Erzeugt jetzt aber die neuen RGBW-Geräte.
Welche CUxD-Version hast Du installiert?

**Comment by LevelOne2k** [comment]
Das habe ich gerade auch mitbekommen das jetzt die RGBW-Geräte erzeugt werden. Aber ich kann leider keine CUxD Geräte im Hue Addon Webif erzeugen.

CUxD-Version 2.4

So sieht es bei mir aus:
<img width="575" alt="Bildschirmfoto 2020-03-29 um 15 58 09" src="https://user-images.githubusercontent.com/25386824/77850963-5a4a9a00-71d6-11ea-801d-3b23ca457f38.png">

**Comment by j-a-n** [comment]
Du musst auf den Info-Button klicken.

**Comment by LevelOne2k** [comment]
lol, alles klar, danke! ^^

**Comment by j-a-n** [comment]
Kein Problem ;-)

**Comment by LevelOne2k** [comment]
Nun hat es geklappt. Kurze Frage noch: Wenn ich die Hue's nun z.B. über die Hue App steuere z.B. ausschalte, dann sehe ich den Status in der CCU am RGBW-Gerät nicht, ist das richtig?

"Beim Ausschalten von Lampen/Gruppen den Parameter transitiontime nicht an die API senden"

habe ich nun auf "Immer" stehen.

**Comment by j-a-n** [comment]
Die Status-Updates sollten funktionieren.
Intervall auf einen Wert größer 0 setzten.
Wenn das alleine nicht hilft, hue-Daemon neu starten.

**Comment by LevelOne2k** [comment]
Es funktioniert leider nicht. Wenn ich die Hue Lampe in der Hue App ausschalte, dann ist sie in der CCU noch eingeschaltet. Oder wenn ich die Farbe in der Hue App ändere, dann bekommt die CCU davon auch nichts mit.

"ntervall in Sekunden, das angibt wie oft der Geräte-Status von der Bridge abgefragt wird (0=Abfrage deaktiviert)"

Steht bei mir auf "5". Den Hue-Daemon habe ich auch schon neu gestartet.

**Comment by j-a-n** [comment]
Was steht im Log?

**Comment by LevelOne2k** [comment]
Ich habe jetzt die ganze CCU mal neu gestartet, nun geht es. Wenn ich in der Hue App etwas verändere, dann sehe ich das in der CCU. Aber wenn ich in der CCU etwas verändere, dann sehe ich das nicht in der Hue App, ist das normal?
