### ISSUE TITLE
RGB Dimmer does only show white colors, not rgb

### ISSUE THREAD

**Issue by hooker78** [j-a-n/homematic-addon-hue#27]
I run version 3.0.1 and CUXD 2.4
When I create an RGB Dimmer, the color setting is not available. Only white temperature can be selected
![rgb1](https://user-images.githubusercontent.com/52243785/77917831-52a0f900-729b-11ea-8c25-e44766bf8e5d.png)
![rgb3](https://user-images.githubusercontent.com/52243785/77917837-53d22600-729b-11ea-8323-b479d5b10e7c.png)
![rgb2](https://user-images.githubusercontent.com/52243785/77917848-56cd1680-729b-11ea-9130-602d7a69245f.png)

**Comment by j-a-n** [comment]
Please provide the "capabilities" of the ZBT-ExtendedColor light.

**Comment by hooker78** [comment]
The lamp is this one here:
[TIN GU 10](https://www.mueller-licht.de/_tool-gesamt_/index.php?Artikel=404005&L=de)

I can change colors for example by:
`tclsh /usr/local/addons/hue/hue.tcl  001788fffe12081c light 1 bri:255  sat:254 rgb:255,0,0`

**Comment by j-a-n** [comment]
Please click on the info button and provide the "capabilities" of the lamp.

**Comment by hooker78** [comment]
![rgb4](https://user-images.githubusercontent.com/52243785/78009881-f80ea800-7341-11ea-9904-6a93e0e8fe9b.png)
I dont see any other infos than this... maybe I am at the wrong place?

**Comment by j-a-n** [comment]
Could you please provide the output of:
`/usr/local/addons/hue/hue.tcl <your-bridge-id> request GET /lights/1`

**Comment by hooker78** [comment]
{"state":{"on":true,"bri":254,"hue":0,"sat":191,"effect":"none","xy":[0.4453,0.4065],"ct":350,"alert":"select","colormode":"ct","reachable":false},"type":"Extended color light","name":"aldi gu22 (1)","modelid":"ZBT-ExtendedColor","manufacturername":"MLI","uniqueid":"d0:cf:5e:ff:fe:43:23:3e-01","swversion":"2.2"}

**Comment by j-a-n** [comment]
Thank you, please try addon version 3.0.2.

**Comment by hooker78** [comment]
works - perfect! Thank you very very much!!!!
