### ISSUE TITLE
Fehlermeldung bei CUxD-RGB-Dimmer erzeugen

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#28]
Hallo @j-a-n , wenn ich ein CUxD-RGB-Dimmer erzeugen möchte, dann bekomme ich diese Fehlermeldung:

```Ein Fehler ist aufgetreten: invalid command name "elseif"```

<img width="934" alt="Bildschirmfoto 2020-04-01 um 14 55 07" src="https://user-images.githubusercontent.com/25386824/78139434-cb818b80-7428-11ea-9205-94d4314b7265.png">

Hue Addon 3.0.3

CUxD 2.4.1

**Comment by j-a-n** [comment]
Behoben in 3.0.4
