### ISSUE TITLE
Farbanzeige stimmt nicht(?)

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#29]
Hallo @j-a-n meine abendliche Beleuchtung ist immer dunkel und orange. Nun zeigt mir die WebUI aber auch Apps in dieser Einstellung an, dass es sich um "schwarz" handelt. Ist das normal?

Eingestellt ist orange.

<img width="916" alt="Bildschirmfoto 2020-04-02 um 17 32 32" src="https://user-images.githubusercontent.com/25386824/78268039-f5f64600-7507-11ea-958b-96ffa18fe0d5.png">

![IMG_5232](https://user-images.githubusercontent.com/25386824/78268178-1de5a980-7508-11ea-9d8d-52db6a2f4164.jpeg)

![IMG_5233](https://user-images.githubusercontent.com/25386824/78268193-21793080-7508-11ea-805d-19d95fc31894.jpeg)

Edit:
Wenn ich auf 100% dimme dann stimmt es.
<img width="913" alt="Bildschirmfoto 2020-04-02 um 17 34 39" src="https://user-images.githubusercontent.com/25386824/78268292-453c7680-7508-11ea-90d8-db6502f8c7c0.png">

![IMG_5234](https://user-images.githubusercontent.com/25386824/78268368-64d39f00-7508-11ea-8310-b453defc35d1.jpeg)

![IMG_5235](https://user-images.githubusercontent.com/25386824/78268376-67ce8f80-7508-11ea-8eb3-40eab38885a3.jpeg)

**Comment by j-a-n** [comment]
Das ist ein sehr dunkles Orange, kein Schwarz. Wie hättest Du es den gerne?

**Comment by LevelOne2k** [comment]
Die Farbe an den Lampen stimmt. Ich dachte nur, der Farbwert in der WebUI und Apps wird falsch angezeigt. Aber dann ist es wohl richtig weil die Lampen ziemlich runter gedimmt sind.

**Comment by j-a-n** [comment]
Ja, wenn Du keine bessere Idee hast, dann lass ich das so.

**Comment by LevelOne2k** [comment]
@j-a-n Meine Idee wäre, wenn es möglich ist, die Farbanzeige unabhängig von der Helligkeit darzustellen.

**Comment by LevelOne2k** [comment]
Eine andere Sache: Kann ich mir Dir außerhalb von Guthib kontakt aufnehmen? Es geht um das Addon, aber ist etwas langwierig. Ob Bug oder nicht Bug usw. Will das hier nicht unnötig zu spammen.

**Comment by j-a-n** [comment]
Das Verhalten ist jetzt in Version 3.0.6 konfigurierbar.
Du kannst mich auch im HM-Forum per PN kontaktieren.

**Comment by LevelOne2k** [comment]
Hm, es sieht immer noch so aus

<img width="920" alt="Bildschirmfoto 2020-04-02 um 23 23 39" src="https://user-images.githubusercontent.com/25386824/78301403-4cc84380-7539-11ea-9029-b20e9fd6d6e6.png">

Da bin ich schon länger nicht mehr angemeldet. Mache ich dann mal und melde mich.

**Comment by LevelOne2k** [comment]
@j-a-n ich sollte vielecht auch mal lesen "... konfigurierbar" ^^

Klappt wunderbar, cool das es optional ist. Danke!
