### ISSUE TITLE
Frage zum Dimmer und Hue

### ISSUE THREAD

**Issue by GoProAndy** [j-a-n/homematic-addon-hue#3]
Hallo,

ich habe folgendes Setup 
CCU2 mit 2.29.22
CuxD 1.11a
Homematic Plugin https://github.com/j-a-n/homematic-addon-hue 0.8.20

Ich möchte folgendes Erreichen:
Wenn ich das Licht in meinen Raum über den Wandschalter (Dimmer HM-LC-Dim1TPBU-FM) einschalte soll meine Philips Hue mit eingeschaltet werden, wenn ich sie über die @Home App oder die CCU Website schalte soll die Philips Hue nicht mit eingeschaltet werden. Die Hue soll also nur geschalten werden wenn ich den Physischen Schalter verwende. Leider hab ich beim Programm nur die Möglichkeit über den DimWert gefunden, hat jemand eine andere Idee?

Danke
Andy

**Comment by j-a-n** [comment]
Hallo Andy,

kannst Du nicht einfach ein Programm bei Tastendruck auslösen?

Wenn "HM-LC-Dim1TPBU-FM" Tastendruck kurz
und
Dimmwert "HM-LC-Dim1TPBU-FM" > 0 (nur prüfen)
dann
Hue an

Ich glaube Deine Frage ist im Homematic-Forum besser aufgehoben.

Grüße
Jan
