### ISSUE TITLE
Gruppen werden teilweise nicht ausgeschaltet 

### ISSUE THREAD

**Issue by mistermakc** [j-a-n/homematic-addon-hue#30]
Obwohl in den Programmen eine Gruppe ausgehen soll, geht sie nicht aus. Erst, wenn ich einen CMD_EXEC Call über das Programm durchführe geht es... Es sind maximal 2 Schaltungen in 10 Sekunden. Bei der 2.4.2 war das Problem nicht. Erst seit der 3.0.9. 
<img width="953" alt="Bildschirmfoto 2020-05-14 um 16 58 19" src="https://user-images.githubusercontent.com/60471340/81950586-68c50780-9604-11ea-80c2-505235df8505.png">
<img width="1216" alt="Bildschirmfoto 2020-05-14 um 17 00 16" src="https://user-images.githubusercontent.com/60471340/81950592-6b276180-9604-11ea-9fcb-e14c115bdbbb.png">

**Comment by j-a-n** [comment]
Was ist "Hue Wohnzimmer" für ein Gerät?
VIR-LG-RGBW-DIM?

**Comment by mistermakc** [comment]
Genau, aber als Gruppe von mehreren Lampen. Darin befindet sich auch ein Innr Plug 120. Transition time steht auf 1. Sollte ich irgendwas ändern?

**Comment by j-a-n** [comment]
Ich habe manchmal ähnliche Probleme.
Ich glaube, dass es am CUxD liegen könnte.
Ich habe Uwe (den Entwickler des CUxD) angeschrieben.
Mal abwarten was er dazu sagt.

**Comment by mistermakc** [comment]
Super, danke. Ja, das hatte ich auch in Erwägung gezogen, da es manchmal geht und manchmal nicht

**Comment by mistermakc** [comment]
Hey Jan, hat Uwe dir schon geantwortet?

**Comment by j-a-n** [comment]
Ja, das Problem ist gefunden.
Ursache ist ein Workaround im CUxD der folgendes Problem beheben soll:
https://homematic-forum.de/forum/viewtopic.php?f=34&t=57266
Der Workaround führt jedoch dazu, dass die Dimmer nur noch eingeschränkt funktionieren.
Ob das die Ursache ist, kann man feststellen wenn man im CUxD-Log nach "DIMMERLEVEL: block" sucht.
Uwe will das Blocken in der nächsten CUxD-Version abschaltbar machen.

**Comment by mistermakc** [comment]
Danke!

**Comment by j-a-n** [comment]
Das Problem wird mit CUxD-Version 2.4.4 behoben.
Im CUXD-Setup muss zusätzlich folgendes gesetzt werden:
```LEVEL-FILTER=0```

**Comment by mistermakc** [comment]
Top, danke! Heißt das die 2.4.4 kommt die Tage oder dauert noch?

**Comment by j-a-n** [comment]
Sollte bald verfügbar sein.

**Comment by j-a-n** [comment]
2.4.4 ist mittlerweile verfügbar. Ist das Problem damit gelöst?

**Comment by mistermakc** [comment]
Habe gestern gesehen. Sieht so aus! Hoffe bei dir auch - danke nochmal für deinen Einsatz!
