### ISSUE TITLE
light is switched to wrong color

### ISSUE THREAD

**Issue by etechnik3r** [j-a-n/homematic-addon-hue#32]
When used with in a Homematic program routine, the connected light sometimes is switched to a wrong color.

This program is supposed to switch the light on and to the color red.
![image](https://user-images.githubusercontent.com/66568418/83976595-3eacef80-a8fb-11ea-9e9b-b2eaf10e1cb7.png)

However, when the program is run the light sometimes switches to blue or white and not to red.

**Comment by j-a-n** [comment]
Please set log level to info and hue api log to command. Then reproduce the problem and provide the log file.

**Comment by etechnik3r** [comment]
This is the requested log file where the light turned to blue instead of red

[log.cgi.txt](https://github.com/j-a-n/homematic-addon-hue/files/4744215/log.cgi.txt)

**Comment by j-a-n** [comment]
You are setting colortemperature (Farbtemperatur) and hue+sat (Farbton+Sättigung).
Please use one or the other.

**Comment by etechnik3r** [comment]
Thank you! Problem solved.
