### ISSUE TITLE
CCU does not restart after uploading addon

### ISSUE THREAD

**Issue by Marks182** [j-a-n/homematic-addon-hue#33]
Hello,

I have a problem after uploading the addon via system control of the CCU3. The WebUI asks me to install the plugin. When I click yes, the CCU3 tries to install/restart and breaks up with red light status. That is why I cannot activate the plugin.

It's only me who has this problem? :-) My CCU3 uses firmware 3.53.26 and CUx-Daemon 2.4.4.

In the past, I used the internal Philips Hue plugin. I deactivated this plugin by deleting files in /usr/local/etc/config/eshlight. Perhaps, I did something wrong here?

Best regards!

**Comment by j-a-n** [comment]
I cannot reproduce the issue. Installed successfully with firmware 3.53.26 and CUxD 2.4.4 in my test setup.
Perhaps the downloaded file is corrupted?
Did you try to extract the hm-hue.tar.gz manually?

**Comment by Marks182** [comment]
First of all, thanks for your fast feedback.

The archive was not corrupted. In the meanwhile, I installed the backup before I deleted the internal Philips Hue plugin. Afterwards, I installed your plugin and it works. I have not configured the addon yet because the internal plugin is already active. This has to be deactivated first, right? Do you know how to deactivate the internal plugin correctly? Unfortunately, there is no solution via WebUI.

**Comment by j-a-n** [comment]
No, you can use both systems parallely.
