### ISSUE TITLE
19-Tasten Fernbedienung über CUxD für Szenen

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#34]
Hi @j-a-n !

Wäre es möglich, eine CUxD 19-Tasten Fernbedienung für Szenen zu erzeugen?

- CUxD Gerätetyp: 28 (System)
- Funktion: Exec
- Geräte-Icon: Fernbedienung 19 Tasten
- Control: Taster

Danke schon mal

**Comment by j-a-n** [comment]
Hallo,
ja, Du kannst eine Fernbedienung anlegen und dann über CMD_LONG Szenen schalten, z.B.:
```
/usr/local/addons/hue/hue.tcl 0234faae189721011 group 1 scene:AY-ots9YVHmAE1f
```
