### ISSUE TITLE
wie einzelne Lampe statt gesamten Raum ausschalten

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#35]
Hallo @j-a-n ,

ich Schalte derzeit so den Gesamten Raum ab
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxx Group 6 on:false```

Es es möglich, so auch eine einzelne Lampe in einem Raum auszuschalten und nicht den gesamten Raum wo sich dann alle Lampen ausschalten?

Danke Dir!

@j-a-n Ich habe nun herausgefunden, dass man die Lampe so ausschalten kann:
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxx light 7 on:false``` 

Aber eine Szene auf die Einzelne Lampe kann so nicht gesetzt werden, zumindest geht es bei mir nicht. Die Lampe schaltet sich so einfach nur ein:
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxx light 7 scene:HBP56egSYS3C0bm``` eigentlich hätte sie so rot mit 1% Helligkeit werden sollen.

**Comment by j-a-n** [comment]
Szenen funktionieren generell nur auf Gruppen, nicht auf einzelnen Lampen.
Mit dem Addon hat das nichts zu tun.
