### ISSUE TITLE
CUxD-RGB-Dimmer zeigt Dimmbereich von 1% bis 7% nicht an

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#36]
Hallo @j-a-n ,

ich weiß nicht ob es ein "Problem" in deinem Addon ist, und ob Du da etwas machen kannst, oder ob das eine Sache von CUxD ist. Jedenfalls zeigt der CUxD-RGB-Dimmer den Dimmbereich von 1% bis 7% nicht an, ab 8% ist alles ok. 

Es wäre klasse, wenn auch der Dimmbereich von 1% bis 7% angezeigt werden könnte. Nachts haben wir ein Nachtlicht mit 1% eingeschaltet, weil die 1% Dimmbereich nicht angezeigt wird, sieht es aus, als ob das Licht ausgeschaltet ist, also der Dimmer steht damit auf "Aus".

Danke Dir!

**Comment by j-a-n** [comment]
Sollte in Version 3.0.14 behoben sein.
