### ISSUE TITLE
Regler/Buttons in PocketControl switchen beim einstellen einer Farbe immer

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#37]
Hallo @j-a-n ,

ich habe für meine Lampen in deinem Addon unter Info einen CUxD-RGB-Dimmer erzeugt. Diesen Dimmer steuere ich mit der App PocketControl.

Ich hatte heute schon zu dem Thema ein Gespräch mit dem Entwickler der App, und er wird sich die Sache auch mal ansehen. 

Nr. 1
Wenn man den Dialog für den Dimmer öffnet, diesen dann einschaltet, dann springt die Ansicht erstmal auf "weiß" die Lampe wird jedoch nicht auf weiß geschaltet, sie hat sich in den Fall nur eingeschaltet und auf grün gestellt, wie sie zuvor eingestellt war. Nach einiger Zeit springt der Button dann von weiß zurück auf Farbe und bleibt dann auch auf Farbe stehen.

Nr. 2
Wenn ich nun mit Absicht auf weiß drücke, weil ich die Lampe weiß haben möchte, dann wird die Lampe auch weiß, aber dann springt der Button von weiß auf Farbe, und bleibt dann auch auf Farbe stehen, die Lampe bleibt aber weiterhin weiß. Wenn ich erneut auf den Button weiß drücke, dann bleibt der auch auf weiß stehen. Ändere ich nun mit dem unteren Regler die Sättigung z.B. von Kaltweiß auf Warmweiß, dann springt der Button und die gesamte Ansicht wieder auf Farbe und bleibt dann auch auf Farbe stehen, die Lampe bleibt aber auch hier weiterhin weiß. Also das was man einstellt, nimmt die Lampe auch an, und bleibt auch so eingestellt. Da Sache hier ist nur, dass sich die Buttons und Ansichten in der App immer Ändern.

Nr 1 passiert immer so, es kann jedes Mal reproduziert werden. Nr 2 passiert eher seltener, ich würde sagen in 4-5 von 10 Fällen.

Ich habe mal ein Video von dem verhalten erstellt, dann mit Du es besser nachvollziehen kannst was da (augenscheinlich) passiert. Ich habe Dir das Video per E-Mail zukommen lassen.

Jetzt ist die Frage, ist das ein Problem von deinem Addon, der App oder CUxD oder ist es einfach nur eine Einstellungssache die ich selber noch irgendwo vornehmen kann/muss.

Vielen Dank schon mal.

**Comment by j-a-n** [comment]
Das Problem könnte in Version 3.1.0 des Addons behoben sein.

**Comment by LevelOne2k** [comment]
Es scheint zu funktionieren, danke dafür. 

Allerdings scheint es so, als würden die Lampen jetzt "ruckeln" bzw. hart die Farbe ändern und es scheint etwas verzögert zu sein. Vorher war das schnell und flüssig "smooth"
