### ISSUE TITLE
After upgrade to Rasperrymatic 3.53.30.20200919 Schaltzustand ein/aus does not work anymore

### ISSUE THREAD

**Issue by hooker78** [j-a-n/homematic-addon-hue#38]
I have upgraded to Rasperrymatic 3.53.30.20200919, now the function Schaltzustand ein/aus does not work inside scripts. If I switch to Toggle true/false, it works.

I use the current version of the add-on. my lamps are from Mueller/Tint

**Comment by j-a-n** [comment]
Seems to be a Problem in either RaspberryMatic or CUxD.
