### ISSUE TITLE
„group“ sendet Status (on:false) nicht an „CUxD-RGB-Dimmer“ und „on:true“ nur auf 95%

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#39]
Hallo @j-a-n ,

wenn ich eine Gruppe so ausschalte
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxxxx group 7 on:false```
Dann bekommt der CUxD-RGB-Dimmer das nicht mit und er bleibt eingeschaltet.

<del>-Wenn ich eine Gruppe so einschalte
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxxxx group 7 on:true hue:8402 sat:140 bri:254```
Dann bleibt der CUxD-RGB-Dimmer bei 95% stehen statt auf 100% zu fahren. / del

Wenn ich die Lampe per „light“ statt „group“ schalte, dann wird dem CUxD-RGB-Dimmer auch alles korrekt übermittelt.

Die Hue Lampen bzw. die Hue-Bridge ist auch in HomeKit über die Home App eingebunden, wenn ich Siri nun sage, dass sie das Licht ausschalten soll, dann ist auch hier der CUxD-RGB-Dimmer noch eingeschaltet.

**Comment by j-a-n** [comment]
Welcher CUxD-RGB-Dimmer bleibt eingeschaltet?
Welche Lampen sind in der Gruppe?

**Comment by LevelOne2k** [comment]
Wie meinst du welcher Dimmer eingeschaltet bleibt?

Es ist bei jeder Lampe der Fall.

**Comment by LevelOne2k** [comment]
@j-a-n , ich habe nun auch festgestellt, dass sich der CUxD-RGB-Dimmer auch nicht mehr ausschaltet, wenn die Lampe so ausgeschaltet wird:
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxxxx light 12 on:false``` 
Dabei handelt es sich um den Lightstrip plus - Modell: LST002

Bei der Hue color Lampe - LCT015 hingegen funktioniert es
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxxxx light 7 on:false```

Bei diesen Lampen funktioniert es auch nicht:
Hue Centris Spot - Modell: 5060730P7_2 / _3 / _4 / _5
Hue Centris Celling - Modell: 5060730P7_01
Hue Argenta Color Spot - Modell: 5062448P7

Es geht also per „group“ und „light“ bei diesen Lampen nicht.

**Comment by nubbel7404** [comment]
@j-a-n und @LevelOne2k guten Abend zusammen,

dieses Problem habe ich auch. Ich habe seit letzter Woche auch die große (5er) Hue Centris Celling und das selbe Problem wie von dir @LevelOne2k beschrieben. Muss du @j-a-n diese Lampen erst in das wunderbare AddOn einbauen? Vielen Dank und einen schönen Tag noch.

**Comment by HookHM** [comment]
Hi @j-a-n bei mir ist das auch so, ich kann das nachstellen. Bei mir ist es der Argenta Color 3er Spot.

Gruß Phil

**Comment by AdlerCentauri** [comment]
Kann man hier noch auf einen Fix hoffen? Das ganze ist schon arg nervig. @j-a-n bitte nicht falsch verstehen, ich meine damit das der Bug arg nervig ist, nicht dich persönlich, du machst tolle Arbeit.

**Comment by AdlerCentauri** [comment]
@j-a-n kannst du das Problem hier denn reproduzieren?
