### ISSUE TITLE
Update of light status in 0.10.9 does not work (on RaspberryMatic)

### ISSUE THREAD

**Issue by torstenkn** [j-a-n/homematic-addon-hue#4]
With update to 0.10.9 the state of devices is no longer retrieved from the hue bridge. However, a reinstallation of 0.10.7 solved the issue.

**Comment by j-a-n** [comment]
Lights or groups? Did you restart hued/ccu after upgrade? Could you please provide some logs?

**Comment by torstenkn** [comment]
I am only using lights. Yes, I multiple times restarted the CCU. However, it was not successful. Immediately after installing the previously installed version 0.10.7 it worked again.
By the way I also had issues with the hue.conf and it seems this also appeared after installation of 0.10.9. Some lights were missing and one non-existing hue light appeared in the config. I fixed this - but this had no influence to the data retrival from the bridge.

The hue.log does not show anything except the "Accepted connection..." entries. Which logs are helpful?

**Comment by torstenkn** [comment]
I am only using lights. Yes, I multiple times restarted the CCU. However, it was not successful. Immediately after installing the previously installed version 0.10.7 it worked again.
By the way I also had issues with the hue.conf and it seems this also appeared after installation of 0.10.9. Some lights were missing and one non-existing hue light appeared in the config. I fixed this - but this had no influence to the data retrival from the bridge.

The hue.log does not show anything except the "Accepted connection..." entries. Which logs are helpful?

**Comment by j-a-n** [comment]
Please set the log level to 4 on the config page. Restart hued.tcl or ccu afterwards. You can download the log file on the config page or from /tmp.

**Comment by j-a-n** [comment]
I managed to reproduce the problem. Fixed in 0.10.10.
