### ISSUE TITLE
Lampen schalten sich nur nacheinander ein

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#40]
Hallo @j-a-n ,

ich habe u.a. die Hue Lampe „Centris - 5er“ Diese ist bei mir die Gruppe 7 und wenn ich die Lampe so einschalte
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxxxx group 7 on:true hue:8402 sat:140 bri:254``` dann schalten sich die 5 Leuchtmittel nur nacheinander ein.

Schalte ich die Lampe hingegen über eine Scene
```/usr/local/addons/hue/hue.tcl xxxxxxxxxxxxxxxxxx group 7 scene:xxxxxxxxxxxxx ``` schalten sich alle Leuchtmittel gleichzeitig ein.

**Comment by j-a-n** [comment]
Normalerweise werden Gruppen-Befehle an die einzelnen Lampen der Gruppe gesendet.
Ab Version 3.0.15 kann der zusätzliche Parameter `group_mode:group` übergeben werden.
Dann wird die Gruppe direkt angesprochen.
Damit greift dann aber das Limit der Bridge von 10 Gruppen-Befehlen pro 10 Sekunden.

**Comment by LevelOne2k** [comment]
Wenn ich in der Hue App eine Zone komplett einschalte oder einen Raum, dann schalten sich auch alle Lampen gleichzeitig ein, oder ist das was anderes?
