### ISSUE TITLE
Helligkeit wird nicht korrekt an CUxD-RGB-Dimmer übermittelt wenn diese in der Hue App eingestellt wird

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#41]
Hallo @j-a-n ,

wenn man die Helligkeit in der Hue App einstellt, dann weicht die Anzeige am CUxD-RGB-Dimmer immer um 2% ab. Also wenn man z.B. 41% in der Hue App einstellt, dann zeigt der CUxD-RGB-Dimmer 43% an, stellt man 25% ein, dann zeigt der CUxD-RGB-Dimmer 27% an usw.

Andersrum wird es korrekt übermittelt, also wenn man 43% am CUxD-RGB-Dimmer einstellt, dann zeigt die Hue App auf 43% an usw.

Edit:
Ich bemerke gerade, dass es auch nicht ganz Synchron ist, wenn die Lampen ausgeschaltet werden. Ich habe gerade die Hue Lampe über den on/off Switch in der Hue App ausgeschaltet, aber der CUxD-RGB-Dimmer steht weiterhin auf 34%.

**Comment by HookHM** [comment]
Hi @j-a-n auch das ist bei mir so und kann auch das nachstellen.

Gruß Phil

**Comment by hooker78** [comment]
I think I have a same / similar observation. It seems the level information is not stored in the CUxD RGB Dimmer - even when I am using the "steuern" function in the add-on manager-site (addons/hue/?)

I can execute this statement 

`/usr/local/addons/hue/hue.tcl 001788fffe12081c light 14  on:true hue:1000 sat:155 bri:255`

and I get back:

```
Status
{
  "on": true,
  "bri": 155,
  "hue": 1000,
  "sat": 100,
  "effect": "none",
  "xy": [
    0.4608,
    0.4107
  ],
  "ct": 370,
  "alert": "select",
  "colormode": "hs",
  "reachable": false
}
```
 


But when I check 
`/addons/xmlapi/statelist.cgi`


I see that level is still 0.


```
<channel name="Hue Kinderzimmer OG Osram e27 RGB (14)" ise_id="18793" index="1" visible="true" operate="true">
<datapoint name="CUxD.CUX2801007:1.LEVEL" type="LEVEL" ise_id="18806" value="0.000000" valuetype="4" valueunit="100%" timestamp="1606602225" operations="7"/>
<datapoint name="CUxD.CUX2801007:1.RGBW" type="RGBW" ise_id="18813" value="rgb(0,0,0,0)" valuetype="20" valueunit="" timestamp="1606602225" operations="3"/>
```
```

**Comment by AdlerCentauri** [comment]
Hallo @j-a-n auch dieses Problem kann und muss ich so leider bestätigen.

**Comment by AdlerCentauri** [comment]
Hallo @j-a-n wann kannst du dich diesem Problem mal annehmen? Aber erstmal wünsche ich schöne Feiertage.

**Comment by j-a-n** [comment]
Ich kann dieses Problem nicht reproduzieren. Wenn ich bei mir eine Lampe oder Gruppe in der Hue-App auf 48% stelle, dann wird das auch am RGBW-Dimmer so angezeigt. Stelle ich den RGBW-Dimmer dann auf 49%, wird dieser Wert auch in der Hue-App übernommen.

**Comment by AdlerCentauri** [comment]
@j-a-n ich werde das nochmal testen.

**Comment by j-a-n** [comment]
Ich schließe das erst mal bis es vielleicht neue Infos gibt.
