### ISSUE TITLE
Frage zur Helligkeit über "pct"

### ISSUE THREAD

**Issue by LevelOne2k** [j-a-n/homematic-addon-hue#43]
HALLO @j-a-n ,

du kennst bestimmt auch die Helligkeitssteuerung über den Befehl "pct" statt "bri". pct geht von 0...100. handelt es sich dabei um % also wäre z.B. pct:75 = 75% ?

**Comment by j-a-n** [comment]
Hallo,
nein pct kenne ich im Zusammenhang mit der Hue API nicht.

**Comment by LevelOne2k** [comment]
<img width="1093" alt="Bildschirmfoto 2020-09-27 um 20 03 50" src="https://user-images.githubusercontent.com/25386824/94372296-9d8db300-00fc-11eb-962a-06ae2f8e3242.png">
