### ISSUE TITLE
Einschalten mit Szene stellt kurz auf 100% Helligkeit

### ISSUE THREAD

**Issue by eikowagenknecht** [j-a-n/homematic-addon-hue#46]
Hallo Jan,

folgende Konfiguration:

- AddOn 3.1.0
- Homematic CMD: /usr/local/addons/hue/hue.tcl ********** group 1 scene:VGnCFmAceSGsSDl

Zum Reproduzieren:
- Lampe auf 100% stellen
- Lampe ausschalten
- Szene mit 5% Helligkeit (z.B. Nachtlicht) über das Addon aktivieren
   - Das Addon macht daraus: [0] [2020-12-13 16:34:32] [1089] api request: 192.168.40.34 - PUT - /api/**********/groups/5/action - {"on":true,"scene":"uFRrgh8naoz7NZ9"}
- Lampe geht kurz auf 100% und dann auf die gewünschte Helligkeit

Nach meinen Erkenntnissen aus ein wenig Herumspielen mit Postman sorgt der Befehl `{"on":true,"scene":"uFRrgh8naoz7NZ9"}` für dieses Verhalten, `{"scene":"uFRrgh8naoz7NZ9"}` hingegen funktioniert genauso wie gewünscht (und wie es auch die Hue App tut).

Wenn ich es richtig sehe muss das `"on":true` also entfallen in dem API call gegen die Hue Bridge.

Würde mich freuen, wenn du das nachvollziehen und korrigieren kannst :-)

Viele Grüße

Eiko

**Comment by j-a-n** [comment]
Hallo Eiko,

das Addon sendet teilweise automatisch "on":true/false Befehle mit, da das on/off in der HM aktuell nur über den Dim-Wert abgebildet wird. Ich habe das jetzt so geändert, dass das bei scene-Befehlen nicht passiert. Schau mal, ob es hilft.
Version 3.1.1

Grüße
Jan

**Comment by eikowagenknecht** [comment]
Super, das scheint es repariert zu haben. Endlich nicht mehr nachts kurz mit voller Helligkeit geblendet werden :-)

Danke für die schnelle Lösung!
