### ISSUE TITLE
ScriptRuntimeError nach Aufruf Gewerk "Licht"

### ISSUE THREAD

**Issue by mbhomie007** [j-a-n/homematic-addon-hue#47]
Hallo,

Wenn ich auf der WebUI das Gewerk "Licht" aufrufe und durchscrolle oder über die WebUI eine Lampe schalte, verursacht dies jedes Mal den folgenden ScriptRuntimeError im Log.
Die ID 1215 ist bei mir das Gewerk "Licht"

`Nov 27 17:27:24 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]
Nov 27 17:25:43 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]
Nov 27 17:25:01 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]
Nov 27 17:11:05 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]`

Es spielt dabei keine Rolle ob gerade die Lampe an oder aus ist.

Das Problem wird nach Installation des Addons verursacht. 
Testweise habe ich das Addon deinstalliert, dann war der ScriptRuntimeError weg, also muss es an dem Addon liegen. 

Viele Grüße
Marco

**Comment by mbhomie007** [comment]
Weitere Error:

`Dec 15 18:42:05 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError:  {    object oRGB = cObj.DPByControl("RGBW_COLOR.RGBW");    integer rgbID = -1;   string rgbValue = "unknown";   string rgbDefaultValue = "rgb(255,255,255,255)";    if (oRGB) {     rgbID = oRGB.ID();     rgbValue = oRGB.Value();     rgbDefaultValue = oRGB.MetaData("DEFAULT").ToString();   }    WriteLine("<tr>");      WriteLine("<td>");       WriteLine("<table width='100%' _height='100%' cellspacing='4'>");         WriteLine("<tr>
);           WriteLine("<td>");             WriteLine("<table class='ControlBtnInfo' style='width: 250px;'>");               WriteLine("<tr>");                 WriteLine("<td style='text-align:left'>");                   WriteLine("<span>${lblColorValue}</span>");                 WriteLine("</td>");                 WriteLine("<td style='text-align:right'>");                   WriteLine("<input type='text' id='colorPicker"#chnId#"'></input>");                 WriteLine("</td>");               WriteLine("</
r>");             Wri
Dec 15 18:42:05 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError:  {    object oWhiteLevel = cObj.DPByControl("COLORTEMP.WHITE");    integer whiteLevelID = -1;   string whiteLevelValue = "-1";   real whiteLevelMin = 2700;   real whiteLevelMax = 6500;   real whiteLevelStep = 50;     if (oWhiteLevel) {     whiteLevelID = oWhiteLevel.ID();     whiteLevelValue = oWhiteLevel.Value();     whiteLevelMin   = oWhiteLevel.MetaData("MIN");     whiteLevelMax   = oWhiteLevel.MetaData("MAX");     ! Check if 
he parameter STEP exists whiteLevelStep   = oWhiteLevel.MetaData("STEP");    }    WriteLine("<tr>");    WriteLine("<td>");      WriteLine("<table class='ControlBtnInfo' style='width: 250px; margin-left: 5px;'>");         WriteLine("<tr>");           WriteLine("<td style='text-align:left'><span>${lblColorTemperatureBR}</span></td>");           WriteLine("<td class='CLASS02546' style='text-align:right'>");             WriteLine("<div class='PercBtn' style='height:35px; line-height:35px; width:100px; backgro
nd-color:#89989b; dis`

**Comment by mbhomie007** [comment]
@j-a-n
Konntest du das Problem nachvollziehen? 

Ich habe es nochmal genau getestet:
Sobald ich auf das Gewerk "Licht" klicke, kommt sofort der oben genannte ScriptRunTimeErrror 1215 im Log. 

Hast du eine Idee wie ich den Fehler finden kann?

**Comment by j-a-n** [comment]
Keine Ahnung wo das herkommt. Hat irgendwas mit der Oberfläche zu tun oder mit cuxd.

**Comment by mbhomie007** [comment]
Scheint ein Error des RaspberryMatic zu sein und nicht wie erst angenommen des Addons.

**Comment by mbhomie007** [comment]
@j-a-n

Hallo, 
Es liegt nach langer Recherche der Profis im Homematic-Forum wohl doch am Addon und nicht an der WebUI. 
Siehe: https://homematic-forum.de/forum/viewtopic.php?f=65&t=63915&start=110

Kannst dir das nochmal bitte anschauen? 

Sobald in der WebUI unter "Geräte und Bedienung" ein Hue Gerät angeklickt wird, kommt sofort der ScriptRunTimeErrror.

**Comment by j-a-n** [comment]
Wie im Forum diskutiert. Das Problem liegt in der CCU bzw. CUxD.
rgbDefaultValue = oRGB.MetaData("DEFAULT");
