### ISSUE TITLE
Helligkeit über Automation wird nicht übernommen.

### ISSUE THREAD

**Issue by detLAN** [j-a-n/homematic-addon-hue#48]
Hallo Jan,

wenn ich in einer Automation sage, dass ich gerne grün und 15% Helligkeit haben möchte, erhalte ich grün aber immer mit 100%.

![hue](https://user-images.githubusercontent.com/64675966/103294614-7c39ad00-49f2-11eb-9fb1-5111927d8cb9.jpg)

Habe jetzt auch mal erst die Farbe, dann die Helligkeit genommen, ändert am Ergebnis leider nichts. Auch wenn ich nur den Farbwert definiere und an der 4 Stelle anstatt der 255 z.B. 30 eintrage, erhalte ich immer eine Helligkeit von 100%

Was mache ich falsch? Probiert mit LST002-1-LedStripsv3 und LCT015-1-A19ECLv5.

Besten Dank
Detlef

Nachtrag: Wenn ich den Farbwert nicht setze, sondern einfach nur den Wert für die Helligkeit, so wird dies auch übernommen. Sowie der Farbwert jedoch hinzugefügt wird, wird die Helligkeit immer auf 100% gesetzt, egal ob ich erst den Farbwert und dann die Helligkeit oder andersherum setze.

**Comment by j-a-n** [comment]
Hallo Detlef,
verwende einfach nur den Farbwert.
rgb(0,255,0) ist helles Grün, rgb(0,25,0) ist dunkles Grün.
Grüße
Jan

**Comment by detLAN** [comment]
Okay, Danke fürs Feedback.

**Comment by HookHM** [comment]
Hallo @j-a-n ,

ich habe das auch mal wie von Dir empfohlen so eingestellt. Leider ist es auch hier so das es manchmal funktioniert, und manchmal nicht.

<img width="1070" alt="Bildschirmfoto 2021-02-23 um 09 20 35" src="https://user-images.githubusercontent.com/55434236/108817597-6abaee80-75b8-11eb-8ace-71d11455da5e.png">

Ich habe es auch mal so versucht, hier verhält es sich gleich, mal funktioniert es, mal nicht.
<img width="1067" alt="Bildschirmfoto 2021-02-23 um 09 21 32" src="https://user-images.githubusercontent.com/55434236/108817671-8c1bda80-75b8-11eb-8a9c-ea991602fb6f.png">

<img width="914" alt="Bildschirmfoto 2021-02-23 um 09 22 16" src="https://user-images.githubusercontent.com/55434236/108817767-b077b700-75b8-11eb-90f6-4ad3d62ccc7e.png">

<img width="1931" alt="Bildschirmfoto 2021-02-23 um 09 22 39" src="https://user-images.githubusercontent.com/55434236/108817775-b40b3e00-75b8-11eb-8c6f-c347ce6e4730.png">

`/usr/local/addons/hue/hue.tcl 001788fffea5e4e4 light 7 on:true hue:0 sat:254 bri:1`

Wäre super wenn Du Dir das Verhalten nochmal ansehen kannst. Danke Dir!

**Comment by detLAN** [comment]
Am einfachsten ist es, die Lampe in der Hue App wie gewünscht einzustellen, anschließend die Werte der Lampe unter Homematic abzuschreiben und diese dann in dem Programm via Script einzubinden:
`system.Exec ("/usr/local/addons/hue/hue.tcl 001788ffxxxxxxxx light 20 on:true rgb:0,255,0 bri:38", &stdout,&stderr);`
Das funktioniert wunderbar und stellt sicher, dass die gleichen Werte via Homematic und Hue genutzt werden.

**Comment by HookHM** [comment]
Hallo @detLAN ,

danke für deine Antwort. Aber ich habe ja einen Beitrag über deinem geschrieben, dass es bei mir auch so nicht funktioniert. Einzig was ich bisher testen konnte was funktioniert ist eine Szene mit der gewünschten Helligkeit und Farbe schalten.

<img width="1059" alt="Bildschirmfoto 2021-02-24 um 13 11 55" src="https://user-images.githubusercontent.com/55434236/108998960-efce0280-76a1-11eb-8482-3c4908885a7e.png">

<img width="1932" alt="Bildschirmfoto 2021-02-24 um 13 12 17" src="https://user-images.githubusercontent.com/55434236/108998977-f52b4d00-76a1-11eb-9818-6b298e016a47.png">

`/usr/local/addons/hue/hue.tcl 001788XXXXXXXXXX group 6 scene:HBP56egSYS3C0bm`

**Comment by detLAN** [comment]
Was möchtest Du den machen, werde nicht ganz schlau daraus? Geht es darum das Licht ein und nach einer vorgegebenen Zeit wieder auszuschalten? Dann brauchst Du zwei Scripte

![pic](https://user-images.githubusercontent.com/64675966/109000020-6ae3e880-76a3-11eb-8de0-2b90adb21a9b.jpg)

Mit dem ersten schaltest Du ein:
`system.Exec ("/usr/local/addons/hue/hue.tcl 001788ffxxxxxxxx light 20 on:true rgb:0,255,0 bri:38", &stdout,&stderr);`

Mit dem zweiten aus:
`system.Exec ("/usr/local/addons/hue/hue.tcl 001788ffxxxxxxxx light 20 on:false rgb:0,255,0 bri:38", &stdout,&stderr);`

**Comment by HookHM** [comment]
Nein, das Licht soll auf 1% gehen und auf rot.

Aber es ist so mit SystemExec auch nicht Sinn der Sache so mit dem Hue Addon zu arbeiten wenn es dafür Dimmer über CUxD gibt. Ich denke das ist ein Bug @j-a-n ?
