### ISSUE TITLE
Farbtemperatur stimmt nicht mit Hue-App überein

### ISSUE THREAD

**Issue by mbhomie007** [j-a-n/homematic-addon-hue#49]
@j-a-n 

Die Farbtemperatur in der WebUI stimmen nicht mit der Hue-App überein.

In der WebUI sind **unterschiedliche** Farbtemperaturen zu sehen:

![Screenshot 2021-01-05 225807](https://user-images.githubusercontent.com/64688879/103705088-bbe03600-4faa-11eb-851e-2f6b5869ebb5.jpg)

In der Hue-App sind aber alle Lampen **gleich** dargestellt (gruppiert), gleiche Helligkeit, gleiche Farbe:

![hue](https://user-images.githubusercontent.com/64688879/103705632-aa4b5e00-4fab-11eb-94a4-48429c5d1dbc.jpg)

**Comment by j-a-n** [comment]
Die Lampen scheinen im Farbmodus (xy) zu sein, dann ist die Farbtemperatur (ct) nicht relevant.
