### ISSUE TITLE
RGB-Dimmer - Anzahl Kanäle nicht wie eingestellt

### ISSUE THREAD

**Issue by mbhomie007** [j-a-n/homematic-addon-hue#50]
@j-a-n 

Bei mir hat jedes Hue-Gerät 16 Kanäle.

![hue1](https://user-images.githubusercontent.com/64688879/103706333-f054f180-4fac-11eb-815b-7b0fb0dc8fce.jpg)

Die Hue-Geräte wurden über das Hue-Addon angelegt.
-> "RGB-Dimmer erzeugen"

![hue2](https://user-images.githubusercontent.com/64688879/103706375-fa76f000-4fac-11eb-88e1-63a6739f4f1f.jpg)

In den Geräteeinstellungen wurde aber "Channels: 1 " eingestellt.

**Warum sind es dann 16 Kanäle?**

![hue3](https://user-images.githubusercontent.com/64688879/103706407-05318500-4fad-11eb-9960-cdc8762f6b11.jpg)

**Comment by j-a-n** [comment]
Das ist eine Frage, die den CUxD betrifft.
