### ISSUE TITLE
Probleme mit non-default HTTP-Port

### ISSUE THREAD

**Issue by DennisGaida** [j-a-n/homematic-addon-hue#51]
Add-On funktioniert mit einer Standard Hue-Bridge. Ich probiere ebenfalls einen conbee / deConz Stick zum laufen zu bekommen. Per IP kann ich diesen konfigurieren, aber Info/Control funktionieren nicht.

Ich habe dann gemerkt dass der HTTP Port immer auf 80 resettet wird. Ich klicke auf "Edit", ändere auf z.B. 8081, speichere und öffne wieder die Edit Maske und der Port ist wieder Port 80. deConz läuft bei mir aber auf einem anderen Port.

Muss ich hier andere Einstellungen vornehmen oder spricht irgendwas gegen non-default HTTP Ports?

**Comment by j-a-n** [comment]
Das Problem mit dem Port ist in der neuen Version 3.1.3 behoben.

**Comment by DennisGaida** [comment]
Konnte ich bestätigen. https://github.com/j-a-n/homematic-addon-hue/commit/f2f6225e53050a81bf620b647530f0d809579b5f fixt das Problem
