### ISSUE TITLE
Farbwert bei Wenn-Bedingung nicht rgb() sondern Zahl

### ISSUE THREAD

**Issue by DennisGaida** [j-a-n/homematic-addon-hue#52]
Ich weiß nicht, ob das nicht anders geht oder ob etwas falsch konfiguriert ist bei mir:

Bei einer RGBW-LED kann ich alles korrekt über das Add-On einstellen / setzen. Auch Programme funktionieren.  
Ich möchte eine Wenn-Bedingung schaffen (wenn Farbwert `rgb(x,y,z)`, dann ...) - leider wird mir der Farbwert als Zahl angezeigt:

![image](https://user-images.githubusercontent.com/2392217/104567707-644b6580-564f-11eb-8f23-2507808e9cb6.png)

Wenn ich mir den State ansehe, ist der `hue` eine Zahl, die Überprüfung wäre aber nicht vollständig, da dann `sat` fehlen würde.

`{"on":true,"bri":254,"hue":6408,"sat":201,"effect":"none","xy":[0.457,0.41],"ct":368,"alert":"select","colormode":"xy","mode":"homeautomation","reachable":true}`

Ist eine Wenn-Abfrage über den Farbewert in `rgb` noch nicht implementiert, funktioniert nicht anders als eine Zahl oder habe ich etwas falsch konfiguriert. Mein Ziel ist abzufragen ob der Farbwert X entspricht um ihn dann falls notwendig zu ändern (Use-Case ist dass die LED wieder auf den Initialwert geschaltet wird nach einem Power-Cycle).

**Comment by j-a-n** [comment]
Das ist wohl eine Einschränkung der CCU oder des CUxD-Geräts.
Da kann ich leider nichts machen.

**Comment by DennisGaida** [comment]
Das verstehe ich.

Können wir dann trotzdem den Wertebereich auf etwas sinnvolles setzen? z.B. Skala von 1-65536 um den Hue-Wert zu überprüfen? Oder kommt das gar nicht so  zurück als Rückgabewert?

**Comment by j-a-n** [comment]
Das müsstest Du mal mit dem Entwickler des CUxD besprechen. Kannst Du nicht einfach auf jede Änderung reagieren und dann in einem Homematic-Skript den Wert prüfen?

**Comment by DennisGaida** [comment]
Gute Idee. Ich habe noch nichts mit Homematic-Skripts gemacht, aber stimmt das sollte funktionieren.

**Comment by DennisGaida** [comment]
Falls jemand sucht, ist sehr einfach und funktioniert. HM-Script ist hier besser als der Standardweg. Wenn-Bedingung bei allem feuern, in der Dann-Bedingung ein If-Verstecken:


**Default (100% und warmweiß) bei einschalten:**
```
var level = dom.GetObject("CUxD.xyz:1.LEVEL").Value();
if (level != 1.0) { dom.GetObject("CUxD.xyz:1.LEVEL").State(1.0); }
var white = dom.GetObject("CUxD.xyz:1.WHITE").Value();
if (white != "2725") {dom.GetObject("CUxD.xyz:1.WHITE").State(2725);}
```
