### ISSUE TITLE
Fehlende Möglichkeit VIR-LG-RGBW-DIM-CH auszuschalten in Regel 

### ISSUE THREAD

**Issue by regnets** [j-a-n/homematic-addon-hue#53]
Hallo,

zuerst mal vielen Dank für das geniale Plugin und die Arbeit die bisher hier reingesteckt wurde. 

Ich hoffe dieses Problem wurde nicht vorher schon gelöst, ich habe leider nichts Passendes in den bisherigen Issues gefunden und auch nichts passenden per Google finden können (wahrscheinlich weil ich nicht weiß, wo nach ich genau suchen muss).

Ich habe folgende Automation:

Beim Hochfahren meines Garagentors (Türkontakt löst aus), sollen automatisch die Rolllade des Fensters zur Garage hochfahren und das Auffahrt-Licht (Philips Hue) eingeschaltet werden. Beim Herunterfahren des Garagentors soll wieder die Rollade geschlossen werden und das Licht ausgeschaltet werden. 

![image](https://user-images.githubusercontent.com/1339599/106320288-f4ee8c00-6272-11eb-98b3-75bb7f547d0e.png)

![image](https://user-images.githubusercontent.com/1339599/106320353-10599700-6273-11eb-9a17-9a53ff8428aa.png)

Das klappt natürlich mit folgenden zwei Programmen ziemlich einfach. Die Philips Lampe ist mit der homematic-addon-hue WebUI angelegt worden per "CUxD-RGB-Dimmer erzeugen" angelegt worden.

Beim Ausschalten in der Regel per Wert (Dimmwert) wird anscheinend der Dimmwert von 1 % als Letztes zur Philips Hue Bridge weitergegeben, weil beim Einschalten des Lichts per Hue App (ohne den Dimm Slider zu nutzen) wird die Lampe mit 1 % eingeschaltet. 

Übersehe ich hier die Möglichkeit das Gerät in der Regel ausschalten? 

Ich denke, die Situation könnte ich lösen in dem ich einen "CUxD Schalter" parallel erzeuge. Jedoch habe ich 2 fast volle Hue Bridges mit etwas über 100 Lampen und das würde dann bedeuten,  dass ich alleine über 200 Lampen Geräte in der CCU hätte.

Gibt es hier eine Möglichkeit auch den RGBW-Dimmer per Programm auszuschalten (es gibt immerhin auch den Ein/Aus Schalter in der Bedienungsoberfläche der CCU.

Vielen Dank schonmal!

Gruß

Andreas

**Comment by j-a-n** [comment]
Hallo Andreas,

das Thema wurde bereits mehrfach diskutiert, z.B. #44.
Die CUxD-Geräte bieten aktuell keine Möglichkeit an- und auszuschalten ohne den Dimmwert zu ändern.

Grüße
Jan
