### ISSUE TITLE
Lampen bei „An“ immer auf 100% statt letzter Zustand

### ISSUE THREAD

**Issue by AdlerCentauri** [j-a-n/homematic-addon-hue#54]
Hallo @j-a-n , die Lampen werden bei „An“ ja immer auf den letzten Dimmwert eingeschaltet. Wäre es optional möglich, diese beim „An“ Befehl auf 100% zu schalten und nicht auf den letzen Dimmwert? Z.B. könnte man die Option auf der Hue-Addon-Konfigurationsseite ein/ausschaltbar machen wie z.B. auch die Option „ Helligkeitswerte in RGB-Werten widerspiegeln. So kann jeder selbst entscheiden ob er beim Einschalten einer Lampe den letzten Zustand haben möchte, oder direkt die vollen 100%.

**Comment by regnets** [comment]
Ich würde mich über so ein Feature auch freuen!

**Comment by HookHM** [comment]
Ich würde mich auch über diese Funktion freuen. Mir wäre es auch lieber, wenn die Lampen immer auf 100% fahren statt des letzten Zustands. Aber das soll ja jeder selbst entscheiden können, daher finde ich die Idee von @AdlerCentauri gut das man es auswählen knann ob man es möchte oder nicht. Was sagst Du dazu @j-a-n

**Comment by HookHM** [comment]
Hallo @j-a-n , kann man hier nochmal fragen.

**Comment by j-a-n** [comment]
Ich habe in der 3.2.4 ein entsprechende Konfiguration eingeführt.

**Comment by HookHM** [comment]
Hallo @j-a-n , das ganze funktioniert noch nicht so ganz reibungslos. Wenn ich eine Lampe z.B. auf 75% einschalte, sie dann ausschalte und dann wieder einschalte, dann sollte sie ja eigentlich auf 100% fahren, aber sie tut dann garnichts, sie bleibt aus. Manchmal geht die Lampe auf dann an also auf 100% aber angezeigt wird der vorherige Wert z.B. 75%.

Das Problem besteht bei einer einzelnen Lampe bzw. einem CUxD-Dimmer nicht. Die oben genannte Fehlfunktion ist eine Gruppe bzw. CUxD-RGB-Dimmer.

**Comment by j-a-n** [comment]
Wenn gar nichts passiert, was steht dann im Log (Log-Level info)?

**Comment by HookHM** [comment]
@j-a-n , wo genau meinst Du denn den Log? In der WebUI, CUxD oder Hue Addon?

**Comment by j-a-n** [comment]
Da Hue Addon Log.

**Comment by HookHM** [comment]
Das hier?
<img width="561" alt="Bildschirmfoto 2021-06-19 um 22 38 38" src="https://user-images.githubusercontent.com/55434236/122654971-34007980-d14f-11eb-8016-69884d8e2319.png">
Weil die Seite bleibt weiß wenn ich auf "Log anzeigen" klicke.
