### ISSUE TITLE
Helligkeit oder Farbe wird nicht eingestellt

### ISSUE THREAD

**Issue by HookHM** [j-a-n/homematic-addon-hue#55]
Hallo @j-a-n ,

wenn ich die Lampe über ein Programm Steuer, dann wird manchmal die Helligkeit oder Farbe nicht eingestellt.

<img width="1066" alt="Bildschirmfoto 2021-02-22 um 18 42 38" src="https://user-images.githubusercontent.com/55434236/108748822-51c22700-753f-11eb-9441-3d21fafb779d.png">

Hier ist es so, dass die Lampe manchmal auf rot geht, aber nicht auf 1%. Oder es ist so, dass die Lampe nicht auf rot geht dafür aber auf 1%. 

Woran kann das liegen? Oder ist das evtl. noch ein Bug durch die Umbauten an CuxD aus diesem Thema https://github.com/j-a-n/homematic-addon-hue/issues/44 @uwe111 ? Ich habe CUxD 2.5.3 installiert

**Comment by j-a-n** [comment]
Duplicate of #48
