### ISSUE TITLE
Fehlermeldung direkt nach Installation 

### ISSUE THREAD

**Issue by Grummelwutz** [j-a-n/homematic-addon-hue#56]
Sobald ich das HUe Addon aufrufe: kommt diese Fehlermeldung:

"Ein Fehler ist aufgetreten: /usr/local/addons/cuxd/cuxd: line 1: syntax error: unexpected word (expecting ")")"

**Comment by mz2872** [comment]
Hallo Jan,
ich versuche auch gerade das addon auf meine CCU3 mit Firmware 3.57.5 zu installieren. Nach dem restart der CCU3 fällt mir auf, dass kein Button "Philips Hue" unter Systemsteuerung zu sehen ist.
Beim Versuch das Addon einzustellen taucht sofort folgende Fehlermeldung am oberen Bildschirmrand auf:

<img width="960" alt="Bildschirmfoto 2021-05-02 um 14 02 06" src="https://user-images.githubusercontent.com/83538947/116813921-a04efb80-ab56-11eb-9df5-4805d2df4d94.png">

Ich habe bereits bei der CCU3 ein Werksreset durchgeführt und das Addon ohne eine Konfiguration versucht zu installieren - gleiches Ergebnis. Was mache ich falsch?

Viele Grüße,
Markus

**Comment by j-a-n** [comment]
Hallo Markus,

Du musst vorher das CUxD-Addon installieren.

Grüße
Jan

**Comment by mz2872** [comment]
Hallo Jan, 
mit dem CUxD-Addon funktioniert's perfekt 👍 
Danke für deinen schnellen Support
VG, Markus
