### ISSUE TITLE
Bitte Hilfe, bin durcheinander - Welches Gerät habe ich da damals hinzugefügt?

### ISSUE THREAD

**Issue by HookHM** [j-a-n/homematic-addon-hue#57]
Hallo @j-a-n ,

ich habe mein Philips Hue System komplett neu aufgesetzt inkl. der Bridge in deinem Plugin und den Geräten in der CCU die durch dein Plugin über CUxD erstellt worden sind.

Ich habe hier ein Gerät, welches in der UI vom Hue Plugin einer Bridge-ID zugewiesen ist, dieses hier:
<img width="929" alt="Bildschirmfoto 2021-05-03 um 00 01 45" src="https://user-images.githubusercontent.com/55434236/116829028-cdc19680-aba2-11eb-9d85-9628cb822837.png">
Da steht ja, dass der Gerätetyp ein "Licht" ist. Aber wenn ich in der CCU nach "CUX4000002" suche, dann ist des dieses Gerät:
<img width="1223" alt="Bildschirmfoto 2021-05-03 um 00 03 43" src="https://user-images.githubusercontent.com/55434236/116829062-0fead800-aba3-11eb-828a-eccdef6c6f45.png">

Ist das Korrekt? Ich weiß nicht mehr, wie ich das Gerät damals hinzugefügt habe, denn es ist ja sozusagen eine 16-Tasten Fernbedienung. In diese Gerät habe ich dann später auch in anderen Kanälen z.B. Szenen manuell eingefügt "/usr/local/addons/hue/hue.tcl 0xx78xxxxxx5xxxe4 group 1 scene:KVBVn30QUtH1E3L" 

<img width="740" alt="Bildschirmfoto 2021-05-03 um 00 08 25" src="https://user-images.githubusercontent.com/55434236/116829271-b636dd80-aba3-11eb-827e-3247d0122092.png">

Wie ist es zu diesem Gerät gekommen? Ich habe es leider nicht mehr in Erinnerung.

Danke schon mal

**Comment by j-a-n** [comment]
Das hast Du wohl manuell angelegt. Das Addon erkennt dass an dem CUxD-Kanal ein Command hinterlegt ist der ein Licht enthält.

**Comment by HookHM** [comment]
Okay danke, dann weiß ich woher das kommt und wie es zu der Zuordnung kam.
