### ISSUE TITLE
Wenn CUxD-RGB Dimmer auf Dimmwert <100 steht und die Farbe geändert wird, wird auf 100% gedimmt

### ISSUE THREAD

**Issue by HookHM** [j-a-n/homematic-addon-hue#58]
Hallo @j-a-n ,

mir ist gerade aufgefallen, dass wenn ein CUxD-RGB Dimmer z.B. auf 20% Dimmwert steht, man dann die Farbe ändert, der Dimmwert dann auf 100% geschaltet wird. Das ist sowohl in der CCU WebUI wie auch in Apps so. 

Wenn der Dimmwert auf 20% steht und man die Farbe ändert, dann sollte der Dimmwert auch auf 20% bleiben und nicht auf 100% schalten.

**Comment by HookHM** [comment]
@j-a-n kannst du das reproduzieren? Der Bug ist ziemlich doof.

**Comment by HookHM** [comment]
Hallo @j-a-n nach über einem Monat kann man doch schon mal eine Antwort bekommen, oder nicht?

**Comment by j-a-n** [comment]
Ich setze das Addon selbst nicht mehr ein, da ich auf Home Assistant umgestiegen bin.
Daher kann ich das aktuell nicht nachstellen.

Es könnte mit der Einstellung "Helligkeitswerte in RGB-Werten widerspiegeln" zu tun haben.
Oder das Problem ist die in #48 beschriebene Übergabe von Farbwerten.

**Comment by HookHM** [comment]
Du setzt deine eigene Software nicht mehr ein? Wie kann man dann jetzt den Bug beseitigen? Ich kann es leider nicht.

**Comment by j-a-n** [comment]
Hast Du es mal mit der Einstellung "Helligkeitswerte in RGB-Werten widerspiegeln" ausprobiert?

**Comment by HookHM** [comment]
Gerade getestet, funktioniert leider auch nicht :-(

Wenn die Helligkeit auf z.B. 40% steht, man die Farbe dann ändert, wird direkt auch zusätzlich auf 100% gestellt :-(

**Comment by j-a-n** [comment]
Hast du nach der Änderung den Hue-Daemon neu gestartet?
Geht die Lampe auf 100% oder nur die Anzeige auf der Oberfläche?

**Comment by HookHM** [comment]
Ja, habe den Daemon neu gestartet, die pid hat sich dann auch geändert.

Die Lampe und die Anzeige geht auf 100%.

**Comment by HookHM** [comment]
@j-a-n Ich setze den RGBW-Dimmer auch nicht in einem Programm ein, es ist also Programm unabhängig. Ich steuere den RGBW-Dimmer direkt an. Der Fehler tritt auf wenn ich den RGBW-Dimmer in der WebUI oder einer App (PocketControl) steuere.

**Comment by j-a-n** [comment]
Schau mal bitte ins Log des CUXD.
Welchen hue.tcl Befehl führt der aus?

**Comment by HookHM** [comment]
Meinst Du das?

`CUX2801003:1	rmax(65535) t(3600s) p(0)
			DIMMER-OLDLEVEL CMD_SHORT(/usr/local/addons/hue/hue.tcl 001788fffea5e4e4 group 9)
			RGBW-LEVEL CMD_LONG(/usr/local/addons/hue/hue.tcl 001788fffea5e4e4 group 9)`

**Comment by HookHM** [comment]
Hallo @j-a-n ist es das was du sehen wolltest?

**Comment by j-a-n** [comment]
Versuch mal Version 3.2.3 und stell "Helligkeitswerte in RGB-Werten widerspiegeln" aus.

**Comment by HookHM** [comment]
Mega! Funktioniert. Die Helligkeit wird nun nicht mehr auf 100% gestellt wenn die Farbe geändert wird. Danke sehr!
