### ISSUE TITLE
Falsche Dimmwerte HUE Lampen

### ISSUE THREAD

**Issue by Draexl** [j-a-n/homematic-addon-hue#59]
Hallo Zusammen,

Folgendes Problem:

Aufbau:
Raspberrymatic 3.57.5.20210525
Hued Add-on von j-a-n 3.2.4
CUx Daemon 2.6

Beim aktivieren des Programm werden nicht die Dimmwerte für die HUE Lampen genommen die im Programm stehen, sondern andere. In diesen Fall immer 40%. Was ist hier falsch?

Programmeinstellung siehe Screenshot
![image](https://user-images.githubusercontent.com/86128006/123626882-9ae9f680-d811-11eb-92f7-151543c157da.png)
![image](https://user-images.githubusercontent.com/86128006/123626894-9de4e700-d811-11eb-9b64-da8b6748eb61.png)
![image](https://user-images.githubusercontent.com/86128006/123626899-a0dfd780-d811-11eb-8667-c8110ecabccf.jpeg)

**Comment by j-a-n** [comment]
Auf was steht die Addon-Einstellung "Helligkeitswerte in RGB-Werten widerspiegeln"?

**Comment by Draexl** [comment]
Ist aktiv.
Siehe Screenschot
![image](https://user-images.githubusercontent.com/86128006/123628773-c40b8680-d813-11eb-9971-b1fe2c148a04.png)

**Comment by j-a-n** [comment]
Dann verwende einfach nur den Farbwert in der Automatisierung.
rgb(0,255,0) ist helles Grün, rgb(0,25,0) ist dunkles Grün.

**Comment by Draexl** [comment]
Aber es geht ja um die Prozentwerte vom Dimmer. Wenn 30% im Programm, kommen 40% zurück.

**Comment by j-a-n** [comment]
Ein RGB-Wert besteht aus 3 Werten. Einer für Rot, einer für Grün und einer für Blau. Gültige Werte sind jeweils 0-255, aus bis ganz hell. Wenn Du "Helligkeitswerte in RGB-Werten widerspiegeln" anschaltest, dann wird über die RGB-Werte auch die Helligkeit beeinflusst (Dimmwert).
1,0,0 ist dann sehr dunkles Rot und 255,0,0 ist dann sehr helles Rot.
