### ISSUE TITLE
CUXD RGBW-Dimmer nicht schaltbar, Status wird nicht aktualisiert

### ISSUE THREAD

**Issue by mbhomie007** [j-a-n/homematic-addon-hue#61]
Hallo @j-a-n 

Ich hatte schon mit @uwe111 geschrieben. 
Vielleicht kannst du hier helfen. 

CUXD Version 2.6.0

![CUXD 2.6.0-1 (1).jpg](https://user-images.githubusercontent.com/64688879/139742900-dc6a9183-87d0-4ffa-8ac7-a0e31eea6b98.jpg)

![CUXD 2.6.0-2 (1).jpg](https://user-images.githubusercontent.com/64688879/139742924-c3bb11c6-649f-4923-8b1e-2d4d683bab46.jpg)

Zuordnung im HUE Addon, alle Geräte werden gefunden.

![Hue Addon mit CUXD 2.6.0 (1).jpg](https://user-images.githubusercontent.com/64688879/139742953-bb97a600-4f79-433a-a241-a40446118924.jpg)

CUXD Version 2.6.2

![CUXD 2.6.2-1 (1).jpg](https://user-images.githubusercontent.com/64688879/139742969-33b21d03-290b-42c0-9e5c-9acce037f914.jpg)

![CUXD 2.6.2-2 (1).jpg](https://user-images.githubusercontent.com/64688879/139742999-918826f4-fe31-4326-bc9f-4a6ab8399f4c.jpg)

Hue Addon, keine Geräte werden mehr gefunden.

![Hue Addon mit CUXD 2.6.2 (1).jpg](https://user-images.githubusercontent.com/64688879/139743017-c5438012-64c5-4434-8988-942e21ef98db.jpg)

In beiden Versionen ist bei CMD-Short und auch CMD-Long das gleiche eingetragen:
/usr/local/addons/hue/hue.tcl 001788fffe7bf2b5 light 13

Mit der CUXD Version 2.6.2 lassen sich nun die HUE Lampen über die WEB-UI der CCU nicht mehr an schalten und auch die Farbe lässt sich nicht mehr ändern.
Lediglich der "AUS" Befehl wir angenommen und die Lampen gehen auch aus.

![Screenshot 2021-10-22 195349 (1).jpg](https://user-images.githubusercontent.com/64688879/139743266-fc3236ca-bd53-4ae5-9dc7-4b0ca36a9796.jpg)

Mit der CUXD Version 2.6.0 geht alles problemlos.

![Screenshot 2021-10-22 195500 (1).jpg](https://user-images.githubusercontent.com/64688879/139743276-7090a95f-c73f-4488-b813-d5428303a444.jpg)

**Comment by mbhomie007** [comment]
Hallo @j-a-n

Wäre sehr lieb wenn du da mal drauf schauen könntest. 
Ich habe mit @uwe111 schon geschrieben, leider kommen wir da nicht weiter.

**Comment by j-a-n** [comment]
Hallo,
sorry, ich habe leider keine Umgebung mehr in der ich das Testen könnte.
