### ISSUE TITLE
Significant delay when used with a Homematic wall switch and a program

### ISSUE THREAD

**Issue by georgbachmann** [j-a-n/homematic-addon-hue#7]
Hello,
I finally managed to get everything working inside my CCU2... great!
When I control the Hue inside the WebUI of Homematic there is no real noticeable delay.
But now I'd like to trigger the lights with a wall-switch. f.e. the HM-RC-2-PBU-FM.
I added a program todo so. It's if switch on, hue on. If switch off, hue off.
That works basically, but there is quite some delay (2-4 seconds).
As you guys here most likely have a similar setup, I'd like to ask how you solved that delay problem?
Cheers,
Georg

**Comment by j-a-n** [comment]
Hi Georg,
as you said there is no delay when controlled by the webui.
So I don't think that this is an issue with the add-on.
Currently I have no idea what could causes the delay.
Please post your question at the homematic forum.
Greetings
Jan

**Comment by georgbachmann** [comment]
Sure, I also don't think it's the addon, I was just hoping you guys might have a similar setup and could tell me about your experiences. Do you personally control your hue with a "Funkschalter für Markenschalter" or similar? What are your experiences?

**Comment by j-a-n** [comment]
I am using homematic wired and rf switches with no noticable delay.
Should be a problem with the switch or the script.

**Comment by georgbachmann** [comment]
And you have a program on your CCU? Or how did you make the RF switch trigger the HUE?
Any tips are very very welcome as I am not that experienced with home-automation so far...
Can you tell me the RF switches that you use?

**Comment by j-a-n** [comment]
Yes, with a program.
Please post your question at the homematic forum.

**Comment by georgbachmann** [comment]
Hey Jan, would you be as kind as to show me (maybe a screenshot or so) your program and wall-switch configuration. In the homematic forum people told me... "yes, programs are slow"... but if you have it working faster, I'd be super glad to see how...

**Comment by j-a-n** [comment]
Here the example with an HM-PB-6-WM55:

Bedingung: Wenn...
HM-PB-6-WM55 - Taste 1
UND
Hue 1 - Helligkeit bei  im Wertebereich kleiner als 1.00 %   

Aktivität: Dann...Vor dem Ausführen alle laufenden Verzögerungen für diese Aktivitäten beenden (z.B. Retriggern).
Hue 1 - Helligkeit auf 100.00 %  

Aktivität: Sonst... Vor dem Ausführen alle laufenden Verzögerungen für diese Aktivitäten beenden (z.B. Retriggern).
Hue 1 - Helligkeit auf 0.00 %
