### ISSUE TITLE
release 1.4.7

### ISSUE THREAD

**Issue by Thomas267** [j-a-n/homematic-addon-hue#8]
Hi Jan,

after downloading and installing release 1.4.7 i still see release 1.4.6 installed. Tried this 2 times. Any ideas?

**Comment by j-a-n** [comment]
Please try version 1.4.8.

**Comment by Thomas267** [comment]
Working now. Thanks a lot.


Gruß
Thomas


Am 14.02.2019 um 20:48 schrieb j-a-n <notifications@github.com<mailto:notifications@github.com>>:


Please try version 1.4.8.
