### ISSUE TITLE
Download aus der CCU WebUI heraus lädt eine "update.cgi"

### ISSUE THREAD

**Issue by CharlyFive** [j-a-n/homematic-addon-hue#9]
Hallo, wenn man aus der CCU WebUI die aktuelle Version laden will, dann wird nicht die Software geladen, sondern eine "update.cgi". 

Bei mir läuft die RaspberryMartic 3.45.7.20190511

Könntest Du das bitte anpassen, danke.

**Comment by j-a-n** [comment]
Behoben in 2.0.10

**Comment by CharlyFive** [comment]
Danke fürs schnelle umsetzen.

Wenn man nun auf "Herunterladen" klickt, dann wird eine neue Seite im selben Tab geöffnet und die aktuelle Version geladen.

Da die neue Seite im selben Tab geöffnet wird, ist die WebUI dann nicht mehr da. Der Link sollte am besten mit einem verweis auf neuen Tab geöffnet werden.

Danke

**Comment by j-a-n** [comment]
Das wäre schön. Dafür müsstest Du Dich aber bitte an eQ-3 wenden.
